services:
  mariadb:
    image: mariadb:touahman
    build: requirements/mariadb/.
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mdb:/var/lib/mysql
    networks:
      - my_network
    secrets:
      - db_user_pass
      - db_root_pass

  nginx:
    image: nginx:touahman
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
    restart: always
    ports: 
      - 443:443
    env_file: .env
    networks:
      - my_network
    volumes:
      - wp:/var/www/wordpress

  wordpress:
    image: wordpress:touahman
    build: requirements/wordpress/.
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    env_file: .env
    networks:
      - my_network
    volumes:
      - wp:/var/www/wordpress
    secrets:
      - wp_user_pass
      - wp_admin_pass
      - db_user_pass

volumes:
  mdb:
    name: mariadb
    driver: local # Specifies that the storage will be on the local filesystem rather than a remote storage system
    driver_opts:
      device: /home/touahman/data/mariadb
      o: bind # Specifies this is a bind mount, which means it creates a direct link to the host directory (you can consider bind, like the symbolic link of a directory)
      type: none
  wp:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/touahman/data/wordpress
      o: bind
      type: none

networks:
  my_network:
    driver: bridge

secrets:
  db_user_pass:
    file: ../secrets/db_password.txt
  db_root_pass:
    file: ../secrets/db_root_password.txt
  wp_admin_pass:
    file: ../secrets/wp_admin_password.txt
  wp_user_pass:
    file: ../secrets/wp_user_password.txt
