services:
  mariadb:
    image: mariadb:touahman
    build: requirements/mariadb/.
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mdb:/var/lib/mysql
    networks:
      - my_network

  nginx:
    image: nginx:touahman
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
    restart: always
    ports: 
      - 443:443
    env_file: .env
    networks:
      - my_network
    volumes:
      - wp:/var/www/wordpress

  wordpress:
    image: wordpress:touahman
    build: requirements/wordpress/.
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    env_file: .env
    networks:
      - my_network
    volumes:
      - wp:/var/www/wordpress

volumes:
  mdb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/touahman/Desktop/data/mariadb
      o: bind
      type: none
  wp:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/touahman/Desktop/data/wordpress
      o: bind
      type: none

networks:
  my_network:
    driver: bridge


