services:
  mariadb:
    image: mariadb:touahman
    build: requirements/mariadb/.
<<<<<<< HEAD
=======
    # container_name: mariadb
>>>>>>> 5ba7c7b5fae3cbe176f53a5cf3c3c1bea8d36b14
    restart: always
    env_file:
      - .env
    volumes:
      - mdb:/var/lib/mysql
    networks:
      - my_network

#nginx
  nginx:
    image: nginx:touahman
    build: requirements/nginx/.
<<<<<<< HEAD
=======
    # container_name: nginx
>>>>>>> 5ba7c7b5fae3cbe176f53a5cf3c3c1bea8d36b14
    depends_on:
      - wordpress
    restart: always
    ports: 
      - 443:443
    env_file: .env
    networks:
      - my_network
    volumes:
      - wp:/var/www/wordpress

#wordpress
  wordpress:
    image: wordpress:touahman
    build: requirements/wordpress/.
    depends_on:
      - mariadb
<<<<<<< HEAD
=======
    # container_name: wordpress
>>>>>>> 5ba7c7b5fae3cbe176f53a5cf3c3c1bea8d36b14
    restart: always
    env_file: .env
    networks:
      - my_network
    volumes:
      - wp:/var/www/wordpress

volumes:
  mdb:
    name: mariadb
    driver: local
    driver_opts:
      # device: /home/mclonglong/data/mariadb
      device: /home/touahman/Desktop/data/mariadb
      o: bind
      type: none
  wp:
    name: wordpress
    driver: local
    driver_opts:
      # device: /home/mclonglong/data/wordpress
      device: /home/touahman/Desktop/data/wordpress
      o: bind
      type: none

networks:
  my_network:
    driver: bridge


