version: "3.9"

services:
# mariadb
  mariadb_database:
    image: mariadb
    build: requirements/mariadb/.
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - mdb:/var/lib/mysql
    networks:
      - NT

#wordpress
  wordpress:
    image: wordpress
    build: requirements/w-press/.
    container_name: wordpress
    restart: always
    env_file: .env
    networks:
      - NT
    volumes:
      - wp:/var/www/html

#nginx
  nginx:
    image: nginx
    build: requirements/nginx/.
    container_name: nginx
    restart: always
    ports: 
      - "443:443"
    env_file: .env
    networks:
      - NT
    volumes:
      - wp:/var/www/html

volumes:
  mdb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/data/mariadb
      o: bind
      type: none
  wp:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/data/wordpress
      o: bind
      type: none

networks:
  NT:


